import { StyleSheet, Dimensions } from "react-native";
import { ScreenHeight } from "react-native-elements/dist/helpers";
import { useFonts, NunitoSans_300Light } from "@expo-google-fonts/nunito-sans";

const darkBlue = "#172041";
const lightBlue = "#26325F";
const cardBlue = "#1b2855";
const orange = "#ff7f00";
const gray = "#8d93a3";
const red = "#d20c0d";
const green = "#1D9440";

// const darkBlue = "whitesmoke";
// const lightBlue = "gray";
// const cardBlue = "white";
// const orange = "#ff7f00";
// const gray = "#8d93a3";
// const red = "#d20c0d";
// const green = "#1D9440";

const screenWidth = Dimensions.get("window").width;
// const primaryColor = "#151D3E";
// const secondaryColor = "#1E2456";
const primaryColor = darkBlue;
const secondaryColor = cardBlue;
const fontColor = "whitesmoke";
const font = "NunitoSans_300Light";
const fontSizeTitle = 14;

const images = StyleSheet.create({
  stockImageSmall: {
    borderRadius: 5,
    resizeMode: "contain",
    height: 40,
    width: 40,
    margin: 10,
  },
  peakLogo: {
    height: 50,
    marginTop: 15,
    marginBottom: -15,
    alignSelf: "center",
  },
  smallCircle: {
    width: 40,
    height: 40,
    margin: 5,
    borderRadius: 25,
  },
});
const views = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: primaryColor,
  },
  cardDevider: {
    height: 2,
    backgroundColor: primaryColor,
  },
  footer: {
    height: 70,
  },
  header: {
    backgroundColor: lightBlue,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    shadowColor: primaryColor,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 5,
    width: screenWidth,
    height: 70,
  },
  headerExpanded: {
    zIndex: 5,
    padding: 0,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: lightBlue,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    shadowColor: secondaryColor,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 5,
    height: ScreenHeight - 70,
    width: screenWidth,
  },
  center: {
    justifyContent: "center",
    marginRight: 10,
  },
  left20: {
    marginLeft: 25,
  },
  selectedChartIcon: {
    height: 30,
    width: (screenWidth - 90) / 6,
    margin: 0,
    justifyContent: "center",
    backgroundColor: orange,
    justifyContent: "center",
    flexDirection: "row",
    borderRadius: 10,
    margin: 5,
    marginTop: 10,
  },
  chartIcon: {
    height: 30,
    width: (screenWidth - 90) / 6,
    margin: 5,
    justifyContent: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 10,
    opacity: 0.2,
  },
  centerContent: {
    justifyContent: "center",
    marginRight: 10,
  },
  centerSection: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    backgroundColor: secondaryColor,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bottomSection: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    backgroundColor: secondaryColor,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  bottomDropdown: {
    backgroundColor: lightBlue,
    marginLeft: 10,
    marginRight: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  twoButtons: {
    flexDirection: "row",
    marginLeft: 15,
    marginRight: 15,
    marginTop: 10,
    justifyContent: "space-between",
  },
  card: {
    backgroundColor: secondaryColor,
    marginLeft: 10,
    marginBottom: 10,
    marginRight: 10,
    borderRadius: 10,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  defaultTop: {
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: secondaryColor,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    paddingBottom: 10,
  },
  defaultView: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: secondaryColor,
  },
  defaultEndView: {
    backgroundColor: secondaryColor,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 2,
    height: 50,
    justifyContent: "center",
    paddingLeft: 30,
    paddingRight: 30,
  },
  segment: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#26325F",
    marginBottom: 1,
    marginLeft: 10,
    marginRight: 10,
  },
  rowCenter: {
    flexDirection: "row",
    justifyContent: "center",
  },
  rowSpaceBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: secondaryColor,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  innerMargin: {
    marginRight: 20,
    marginLeft: 20,
    marginTop: 15,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  columCenter: {
    flexDirection: "column",
    justifyContent: "center",
    marginRight: 10,
    height: 50,
    paddingLeft: 15,
    // backgroundColor: "white",
  },
  slider: {
    marginTop: 10,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 15,
  },
  GIACard: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: orange,
    marginLeft: 14,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
  },
  GIACardUnselected: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: orange,
    marginLeft: 14,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
    opacity: 0.5,
  },
  ISACard: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#FC007A",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
  },
  ISACardUnselected: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#FC007A",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
    opacity: 0.5,
  },
  practiceCard: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#00E1FD",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 14,
    flexDirection: "column",
  },
  practiceCardUnselected: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#00E1FD",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 14,
    flexDirection: "column",
    opacity: 0.5,
  },
  transparentBlack: {
    position: "absolute",
    height: 50,
    width: 50,
    backgroundColor: "black",
    borderRadius: 25,
    opacity: 0.1,
  },
  hight50: {
    height: 50,
    width: 50,
    margin: 5,
  },
  accountCard: {
    height: ScreenHeight / 3.4 - 40,
    justifyContent: "center",
    marginLeft: 15,
  },
  absoluteEnd: {
    position: "absolute",
    right: 10,
    height: "100%",
    justifyContent: "center",
  },
});
const buttons = StyleSheet.create({
  titleBack: {
    alignSelf: "flex-start",
    zIndex: 2,
  },
  headerButton: {
    // backgroundColor: orange,
    borderColor: orange,
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: "center",
  },
  orangeFill: {
    width: "48%",
    height: 45,
    paddingTop: 3.5,
    alignSelf: "center",
    backgroundColor: orange,
    borderRadius: 10,
  },
  noFill: {
    width: "48%",
    height: 45,
    paddingTop: 2,
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: orange,
  },
  selectedBuy: {
    backgroundColor: secondaryColor,
    width: "50%",
    borderTopLeftRadius: 10,
    color: "white",
    textAlign: "center",
    paddingTop: 14,
  },
  unselectedBuy: {
    backgroundColor: primaryColor,
    height: 50,
    width: "50%",
    borderTopLeftRadius: 10,
    color: "white",
    borderWidth: 2,
    borderColor: secondaryColor,
    textAlign: "center",
    paddingTop: 14,
  },
  selectedSell: {
    backgroundColor: secondaryColor,
    width: "50%",
    borderTopRightRadius: 10,
    color: "white",
    textAlign: "center",
    paddingTop: 14,
  },
  unselectedSell: {
    backgroundColor: primaryColor,
    height: 50,
    width: "50%",
    borderTopRightRadius: 10,
    color: "white",
    borderWidth: 2,
    borderColor: secondaryColor,
    textAlign: "center",
    paddingTop: 14,
  },
  settingsButtonTop: {
    height: 50,
    backgroundColor: secondaryColor,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginBottom: 2,
    marginTop: 5,
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  settingsButton: {
    height: 50,
    backgroundColor: secondaryColor,
    marginBottom: 2,
    justifyContent: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  settingsButtonBottom: {
    height: 50,
    backgroundColor: secondaryColor,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    flexDirection: "column",
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
  },
});
const texts = StyleSheet.create({
  white13: {
    color: "white",
    fontSize: 13,
    fontFamily: font,
  },
  faded15: {
    color: "white",
    opacity: 0.75,
    marginRight: 15,
    fontSize: 15,
    fontFamily: font,
  },
  white15: {
    color: "white",
    fontSize: 15,
    fontFamily: font,
  },
  white20: {
    color: "white",
    fontSize: 20,
    fontFamily: font,
  },
  white25: {
    color: "white",
    fontSize: 25,
    fontFamily: font,
    fontWeight: "700",
  },
  white30: {
    fontSize: 30,
    color: "white",
    fontFamily: font,
  },
  gray: {
    fontSize: 18,
    marginTop: 10,
    marginLeft: 15,
    marginBottom: 10,
    color: gray,
  },
  chartTextButton: {
    color: "white",
    fontFamily: font,
    opacity: 0.9,
  },
  infoText: {
    color: "white",
    opacity: 0.7,
    marginTop: 10,
    marginRight: 10,
    marginLeft: 10,
    marginBottom: 10,
    fontSize: 15,
    fontFamily: font,
  },
  buttonText: {
    color: "white",
    textTransform: "none",
    fontFamily: font,
    fontSize: 15,
  },
  orangeButtonText: {
    color: orange,
    fontFamily: font,
    textTransform: "none",
    fontSize: 15,
  },
  tradeOrangeText: {
    color: orange,
    fontFamily: font,
    fontSize: 17,
    alignSelf: "center",
    marginLeft: 30,
    letterSpacing: 1,
  },
  amountOfShares: {
    width: 75,
    color: orange,
    textAlign: "center",
    borderRadius: 7,
    fontSize: 15,
    fontWeight: "bold",
    backgroundColor: "gray",
  },
  pageButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 22,
    textTransform: "none",
    fontFamily: font,
  },
  stockName: {
    fontSize: 13,
    color: "red",
    fontFamily: font,
    //change to white13
  },
  stockTicker: {
    color: gray,
    fontFamily: font,
    letterSpacing: 1.5,
    fontWeight: "normal",
    textTransform: "uppercase",
    fontSize: 10,
  },
  price: {
    borderRadius: 10,
    color: fontColor,
    fontFamily: font,
    alignSelf: "flex-end",
  },
  green: {
    fontSize: 12,
    color: green,
    fontWeight: "bold",
    alignSelf: "flex-end",
    fontFamily: font,
  },
  red: {
    fontSize: 12,
    color: red,
    fontWeight: "bold",
    alignSelf: "flex-end",
    fontFamily: font,
  },
  center: {
    fontSize: 14,
    fontFamily: font,
    color: "gray",
    textAlign: "center",
    alignSelf: "center",
    margin: 5,
  },
});
const inputs = StyleSheet.create({
  input: {
    width: screenWidth - 80,
    height: 40,
    backgroundColor: "lightgray",
    marginTop: 8,
    marginBottom: 0,
    alignSelf: "center",
    padding: 7,
    borderRadius: 10,
  },
});
const styles = StyleSheet.create({
  //buttons
  //--page back button
  pageButton: {
    alignSelf: "flex-start",
    zIndex: 2,
  },

  //----------------------------------
  //Text
  pageButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 22,
    textTransform: "none",
    fontFamily: font,
  },

  //--company name (small)--
  font30: {
    fontSize: 30,
    color: "red",
    fontFamily: font,
  },
  font20: {
    color: "white",
    fontSize: 20,
  },
  listText1: {
    color: "black",
    fontFamily: font,
  },
  listText2: {
    color: "black",
    opacity: 0.85,
    marginRight: 15,
    fontSize: 14,
    fontFamily: font,
  },
  infoText: {
    color: "red",
    opacity: 0.7,
    marginTop: 10,
    marginRight: 10,
    marginLeft: 10,
    marginBottom: 10,
    fontSize: 15,
    fontFamily: font,
  },
  stockName: {
    fontSize: 13,
    fontFamily: font,
    fontWeight: "bold",
    color: "white",
    fontFamily: "NunitoSans_300Light",
    backgroundColor: "red",
  },
  //--stock ticker (small/faded)--
  stockTicker: {
    color: gray,
    fontFamily: font,
    letterSpacing: 1.5,
    fontWeight: "normal",
    textTransform: "uppercase",
    fontSize: 10,
    backgroundColor: "red",
  },
  //--current stock price--
  price: {
    borderRadius: 10,
    color: fontColor,
    fontFamily: font,
    alignSelf: "flex-end",
    backgroundColor: "red",
  },
  //--stock price change/percent/color
  green: {
    fontSize: 12,
    color: green,
    fontWeight: "bold",
    alignSelf: "flex-end",
    fontFamily: font,
    backgroundColor: "red",
  },
  red: {
    fontSize: 12,
    color: red,
    fontWeight: "bold",
    alignSelf: "flex-end",
    fontFamily: font,
    backgroundColor: "red",
  },

  //views
  //- top section of cards
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "pink",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  defaultTop: {
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: "red",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  sharesView: {
    height: 50,
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: "red",
    //centersection
    flexDirection: "row",
    justifyContent: "space-between",
  },
  defaultView: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: "red",
  },
  innerCardView: {
    flexDirection: "column",
    justifyContent: "center",
    marginRight: 10,
    height: 50,
    backgroundColor: "red",
    //views.columcenter
  },
  infoContentsBottom: {
    backgroundColor: "red",
    marginLeft: 10,
    marginRight: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  //segments on the info dropdown
  segment: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "pink",
    marginBottom: 1,
    marginLeft: 10,
    marginRight: 10,
  },
  segmentContents: {
    flexDirection: "column",
    justifyContent: "center",
    height: 50,
  },
  //vv remove
  // infoCardTop: {
  //   marginTop: 10,
  //   marginLeft: 10,
  //   marginRight: 10,
  //   backgroundColor: secondaryColor,
  //   borderTopLeftRadius: 10,
  //   borderTopRightRadius: 10,
  //   flexDirection: "row",
  //   justifyContent: "space-between",
  // },
  //--stock name and ticker view for positioning
  stockContainer: {
    justifyContent: "center",
    marginRight: 10,
    backgroundColor: "pink",
  },
  //--view to position contense in a row
  rowView: {
    display: "flex",
    marginRight: 30,
    justifyContent: "space-between",
    flexDirection: "row",
  },
  //--spaces out content
  cardTopList: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "yellow",
    //views.rowspace
  },
  //--row center
  viewRowCenter: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 5,
  },
  //--card--
  card: {
    backgroundColor: "green",
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 0,
    marginRight: 10,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  peakLogo: {
    height: 50,
    marginTop: 15,
    marginBottom: -15,
    alignSelf: "center",
    backgroundColor: "red",
  },
  twoButtons: {
    flexDirection: "row",
    marginLeft: 15,
    marginRight: 15,
    marginTop: 10,
    backgroundColor: "red",
  },
  //--chart container view
  chartContainer: {
    backgroundColor: secondaryColor,
    marginRight: 10,
    marginLeft: 10,
    marginTop: 2,
  },
  // chartButtons: {
  //   flexDirection: "row",
  //   justifyContent: "space-evenly",
  // },
  //---------------------------------------------------------
  statusBar: {
    backgroundColor: primaryColor,
  },
  container: {
    flex: 1,
    backgroundColor: primaryColor,
  },

  //-------------------navbar---------------------
  navBar: {
    // position:'absolute',
    // bottom:0,
    padding: 10,
    backgroundColor: "#26325F",
    width: screenWidth,
    justifyContent: "space-evenly",
    flexDirection: "row",
    elevation: 10,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  footer: {
    height: 70,
  },
  //-----------------------------------------------------------
  accordionHeader: {
    backgroundColor: secondaryColor,
    height: 50,
    width: screenWidth,
  },
  chartInterval: {
    color: "white",
    fontSize: 15,
    fontFamily: font,
    padding: 5,
  },
  logo: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderColor: "ghostwhite",
    backgroundColor: "#222948",
    borderRadius: 10,
    alignSelf: "center",
  },
  buttonContainer: {
    paddingBottom: 60,
    width: "80%",
    alignSelf: "center",
  },
  //---------header-----------------------------

  // headerBuffer: {
  //   height: 75,
  // },

  headerBall: {
    backgroundColor: orange,
    borderRadius: 20,
    color: "white",
  },
  catagory: {
    position: "absolute",
    right: 20,
    bottom: 10,
    fontFamily: font,
    fontSize: 20,
    backgroundColor: "transparent",
  },

  newsCard: {
    backgroundColor: secondaryColor,
    margin: 10,
    padding: 20,
  },

  priceView: {
    // height: "50px",
    // width: "50px",
    borderColor: "whitesmoke",
    borderWidth: 2,
  },
  percentage: {
    fontSize: 12,
    fontFamily: font,
  },
  green: {
    fontSize: 12,
    color: green,
    fontWeight: "bold",
    alignSelf: "flex-end",
  },
  red: {
    fontSize: 12,
    color: red,
    fontWeight: "bold",
    alignSelf: "flex-end",
  },
  text: {
    fontSize: fontSizeTitle,
    fontFamily: font,
    color: fontColor,
    margin: 4,
  },
  textCenter: {
    fontSize: fontSizeTitle,
    fontFamily: font,
    color: fontColor,
    margin: 4,
    textAlign: "center",
  },
  centeredText: {
    fontSize: fontSizeTitle,
    fontFamily: font,
    color: fontColor,
  },
  titleText: {
    color: fontColor,
    fontFamily: font,
    letterSpacing: 2.5,
    fontWeight: "900",
    marginLeft: 20,
    fontSize: fontSizeTitle,
    margin: 1,
    fontSize: 15,
  },
  newsTitle: {
    color: fontColor,
    fontFamily: font,
    fontWeight: "700",

    fontSize: fontSizeTitle,
    margin: 4,
  },
  image: {
    borderRadius: 3,
    borderColor: "gainsboro",
    resizeMode: "contain",
    height: 40,
    width: 40,
    margin: 10,
    // backgroundColor: "white",
  },
  detailsImage: {
    marginTop: 20,
    marginBottom: 30,
    borderRadius: 40,
    resizeMode: "contain",
    justifyContent: "center",
    alignSelf: "center",
    height: 80,
    width: 80,
    // backgroundColor: "white",
  },
  avatarSmall: {
    margin: 20,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 50,
    resizeMode: "contain",
  },
  footerText: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    color: fontColor,
  },
  rowSpaced: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rowAround: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  //------------------------registration------------
  welcomeCard: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: secondaryColor,
    borderRadius: 15,
    height: 500,
  },
  logoStyle1: {
    height: screenWidth / 4,
    width: "25%",
    marginTop: 70,
    alignSelf: "center",
    resizeMode: "contain",
  },
  logoStyle2: {
    height: screenWidth / 3,
    width: "40%",
    marginTop: -12,
    marginBottom: 0,
    alignSelf: "center",
    resizeMode: "contain",
  },
  signupCard: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: secondaryColor,
    borderRadius: 15,
  },
  topView: {
    width: screenWidth,
    height: 50,
    backgroundColor: "red",
  },
  input: {
    width: screenWidth - 80,
    height: 40,
    backgroundColor: "pink",
    marginTop: 8,
    marginBottom: 0,
    alignSelf: "center",
    padding: 7,
    borderRadius: 10,
  },
  buttonReg: {
    width: screenWidth / 2,
    height: 40,
    backgroundColor: orange,
    alignSelf: "center",
    marginTop: 20,
    marginRight: screenWidth / 4 - 20,
    marginLeft: screenWidth / 4 - 20,
    borderRadius: 13,
  },
  buttonText: {
    color: "blue",
    //moved to texts
    textTransform: "none",
    fontFamily: font,
    fontSize: 15,
  },
  orangeButtonText: {
    color: orange,
    fontWeight: "bold",
    textTransform: "none",
    backgroundColor: "red",
  },
  head1: {
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    marginLeft: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  head2: {
    color: "white",
    fontWeight: "100",
  },
  loadBar: {
    height: 4,
    width: screenWidth - 80,
    backgroundColor: "#8d93a3",
    marginLeft: 40,
    borderRadius: 50,
    marginBottom: 20,
  },
  loadBar2Compleated: {
    backgroundColor: orange,
    height: 4,
    width: (screenWidth - 80) / 5,
    borderRadius: 50,
  },
  loadBar3Compleated: {
    backgroundColor: orange,
    height: 4,
    width: ((screenWidth - 80) / 5) * 2,
    borderRadius: 50,
  },
  loadBar4Compleated: {
    backgroundColor: orange,
    height: 4,
    width: ((screenWidth - 80) / 5) * 3,
    borderRadius: 50,
  },
  loadBar5Compleated: {
    backgroundColor: orange,
    height: 4,
    width: screenWidth - 80,
    borderRadius: 50,
  },
  warning: {
    color: "red",
    marginTop: 5,
    fontSize: 14,
    fontFamily: "Futura",
    marginLeft: 20,
  },
  noWarning: {
    marginTop: 5,
    opacity: 0,
    fontFamily: "Futura",
  },
  imageContainer: {
    flex: 1,
    height: "28%",
    alignItems: "center",
    marginBottom: "2%",
    marginTop: 50,
    backgroundColor: "red",
  },
  bottomSubText: {
    color: "white",
    marginTop: 8,
    fontSize: 15,
  },
  hyperlinkText: {
    color: "#FF8001",
    fontWeight: "bold",
  },
  //--------------------menuscreen--------------------
  avatar: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 50,
    resizeMode: "cover",
    marginTop: 20,
  },
  menuName: {
    fontSize: 16,
    fontFamily: font,
    color: fontColor,
    alignSelf: "center",
    textAlign: "center",
    fontWeight: "bold",
  },
  menuEmail: {
    fontSize: 14,
    fontFamily: font,
    color: "red",
    textAlign: "center",
    fontWeight: "100",
    alignSelf: "center",
  },
  settingsButton: {
    height: 50,
    backgroundColor: "red",
    marginBottom: 2,
    justifyContent: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  settingsButtonTop: {
    height: 50,
    backgroundColor: "red",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginBottom: 2,
    marginTop: 5,
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: 10,
    marginRight: 10,
  },
  settingsButtonBottom: {
    height: 50,
    backgroundColor: "red",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    flexDirection: "column",
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  settingsCard: {
    marginLeft: 20,
    marginRight: 20,
    backgroundColor: "red",
  },
  buttonTextSettings: {
    color: "white",
    fontWeight: "bold",
    textTransform: "none",
    backgroundColor: orange,
  },
  logout: {
    alignSelf: "center",
    justifyContent: "center",
    width: "45%",
    height: 45,
    borderColor: orange,
    borderWidth: 2,
    borderRadius: 14,
    marginTop: 10,
  },
  logoutText: {
    color: orange,
    fontWeight: "bold",
  },
  //--------history---------
  cardHeader: {
    fontSize: 18,
    marginTop: 10,
    marginLeft: 15,
    marginBottom: 10,
    color: "red",
  },
  cardDevider: {
    height: 2,
    backgroundColor: "red",
  },
  cardHistory: {
    backgroundColor: secondaryColor,
    marginLeft: 10,
    marginBottom: 5,
    marginTop: 5,
    marginRight: 10,
    borderRadius: 10,
    shadowColor: "red",
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  historyAction: {
    fontSize: 10,
    color: "white",
    fontWeight: "100",
    color: gray,
  },
  historyValueBox: {
    position: "absolute",
    right: 10,
    height: "100%",
    justifyContent: "center",
    backgroundColor: "red",
  },

  //------companyScreen------------

  priceInfo: {
    fontSize: 25,
    color: "whitesmoke",
    fontWeight: "100",
  },
  percentInfo: {
    fontSize: 12,
    color: "whitesmoke",
    fontWeight: "bold",
    letterSpacing: 2,
    alignSelf: "flex-end",
  },

  chartIcon: {
    height: 30,
    width: (screenWidth - 90) / 6,
    margin: 5,
    justifyContent: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 10,
    opacity: 0.2,
    backgroundColor: "red",
  },
  selectedChartIcon: {
    height: 30,
    width: (screenWidth - 90) / 6,
    margin: 0,
    justifyContent: "center",
    backgroundColor: "red",
    justifyContent: "center",
    flexDirection: "row",
    borderRadius: 10,
    margin: 5,
    marginTop: 10,
  },
  chartTextButtonOrange: {
    color: orange,
    opacity: 1,
    alignSelf: "center",
  },
  chartIconOrange: {
    height: 30,
    width: "16%",
    margin: 0,
    borderWidth: 1,
    borderColor: orange,
    color: orange,
    justifyContent: "center",
    borderRadius: 10,
  },
  orangeFillButton: {
    width: "48%",
    height: 45,
    paddingTop: 3.5,
    alignSelf: "center",
    backgroundColor: "red",
    borderRadius: 10,
  },
  FavouriteButton: {
    width: "48%",
    height: 45,
    paddingTop: 2,
    alignSelf: "center",
    borderWidth: 2,
    borderRadius: 10,
    borderColor: orange,
    backgroundColor: "red",
  },

  infoCardBottom: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    backgroundColor: "red",
    //views.bottomSection
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  infoSection: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    backgroundColor: "red",
    //views.centerSection
    flexDirection: "row",
    justifyContent: "space-between",
  },
  infoTopText: {
    color: "white",
    fontSize: 15,
    marginLeft: 15,
  },
  //trade

  selectedBuyButton: {
    backgroundColor: secondaryColor,
    width: "50%",
    borderTopLeftRadius: 10,
    color: "white",
    textAlign: "center",
    paddingTop: 14,
  },
  unselectedBuyButton: {
    backgroundColor: primaryColor,
    height: 50,
    width: "50%",
    borderTopLeftRadius: 10,
    color: "white",
    borderWidth: 2,
    borderColor: secondaryColor,
    textAlign: "center",
    paddingTop: 14,
  },
  selectedSellButton: {
    backgroundColor: secondaryColor,
    width: "50%",
    borderTopRightRadius: 10,
    color: "white",
    textAlign: "center",
    paddingTop: 14,
  },
  unselectedSellButton: {
    backgroundColor: primaryColor,
    height: 50,
    width: "50%",
    borderTopRightRadius: 10,
    color: "white",
    borderWidth: 2,
    borderColor: secondaryColor,
    textAlign: "center",
    paddingTop: 14,
  },

  defaultCard: {
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 2,
    width: screenWidth - 30,
    backgroundColor: secondaryColor,
    borderRadius: 10,
  },
  defaultInnerView: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    marginBottom: 10,
  },
  defaultEndView: {
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    paddingBottom: 10,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 2,
    backgroundColor: "red",
  },

  tradeText: {
    color: "white",
    fontSize: 15,
    alignSelf: "center",
    marginLeft: 30,
    letterSpacing: 0.5,
    marginRight: 30,
    backgroundColor: "red",
  },
  tradeOrangeText: {
    color: orange,
    fontSize: 17,
    fontWeight: "bold",
    alignSelf: "center",
    marginLeft: 30,
    letterSpacing: 0.5,
    marginRight: 30,
    backgroundColor: "red",
  },
  sliderView: {
    width: screenWidth - 30,
    marginTop: 2,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: secondaryColor,
  },
  sliderText: {
    marginRight: 30,
    marginLeft: 30,
    marginTop: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "red",
  },
  yourShares: {
    color: "white",
    fontSize: 15,
    fontFamily: font,
    backgroundColor: "red",
  },
  amountOfShares: {
    width: 75,
    color: orange,
    textAlign: "center",
    borderRadius: 25,
    fontSize: 15,
    fontWeight: "bold",
    backgroundColor: "red",
  },

  tradeReviewButton: {
    alignSelf: "center",
    justifyContent: "center",
    width: "48%",
    height: 45,
    backgroundColor: orange,
    borderRadius: 14,
    marginTop: 30,
  },
  tradeCancleButton: {
    alignSelf: "center",
    justifyContent: "center",
    width: "48%",
    height: 45,
    backgroundColor: primaryColor,
    borderRadius: 14,
    marginTop: 30,
    borderWidth: 2,
    borderColor: orange,
  },
  portfolioInvested: {
    height: 70,
    width: "48%",
    backgroundColor: secondaryColor,
    flexDirection: "row",
    justifyContent: "center",
    borderRadius: 10,
  },

  portfolioChartHolder: {
    backgroundColor: secondaryColor,
    paddingBottom: 10,
    margin: 15,
    borderRadius: 10,
  },
  backgroundCard: {
    backgroundColor: secondaryColor,
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 5,
    marginRight: 10,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  backgroundSmallCardx3: {
    backgroundColor: secondaryColor,
    width: 130,
    height: 150,
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 0,
    marginRight: 0,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
});

export { styles, buttons, views, texts, images, inputs };
