import { StyleSheet, Dimensions } from "react-native";
import { ScreenHeight } from "react-native-elements/dist/helpers";
import { Colors } from "react-native-paper";
import Constants from "expo-constants";
import { or } from "react-native-reanimated";

const darkBlue = "#172041";
const lightBlue = "#26325F";
const cardBlue = "#1b2855";
const orange = "#ff7f00";
const gray = "#8d93a3";
const red = "#d20c0d";
const green = "#1D9440";

// const darkBlue = "whitesmoke";
// const lightBlue = "gray";
// const cardBlue = "white";
// const orange = "#ff7f00";
// const gray = "#8d93a3";
// const red = "#d20c0d";
// const green = "#1D9440";

const screenWidth = Dimensions.get("window").width;
// const primaryColor = "#151D3E";
// const secondaryColor = "#1E2456";
const primaryColor = darkBlue;
const secondaryColor = cardBlue;
const fontColor = "whitesmoke";
const font = "normal";
const fontSizeTitle = 15;

const styles = StyleSheet.create({
  statusBar: {
    backgroundColor: primaryColor,
  },
  container: {
    flex: 1,
    backgroundColor: primaryColor,
    // marginTop: Constants.statusBarHeight,
  },
  pageButton: {
    alignSelf: "flex-start",
    zIndex: 2,
  },
  pageButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 22,
    textTransform: "none",
  },
  //-------------------navbar---------------------
  navBar: {
    backgroundColor: "#26325F",
    width: screenWidth,
    height: 70,

    // borderTopLeftRadius: 20,
    // borderTopRightRadius: 20,
    justifyContent: "space-evenly",
    flexDirection: "row",
    shadowColor: "white",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 10,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    shadowOpacity: 1,
  },
  navButtonView: {
    width: "20%",
    height: "100%",
    margin: 0,
    // backgroundColor:'white'
  },
  navButton: {
    width: "100%",
    height: "100%",
    margin: 0,
    // backgroundColor:'white'
  },
  footer: {
    width: screenWidth,
    height: 70,
  },
  //-----------------------------------------------------------
  accordionHeader: {
    backgroundColor: secondaryColor,
    height: 50,
    width: screenWidth,
  },
  chartInterval: {
    color: "white",
    fontSize: 15,
    fontFamily: font,
    padding: 5,
  },
  logo: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderColor: "ghostwhite",
    backgroundColor: "#222948",
    borderRadius: 10,
    alignSelf: "center",
  },
  button: {
    alignSelf: "center",
    justifyContent: "center",
    width: "45%",
    height: 45,
    backgroundColor: orange,
    borderRadius: 14,
    marginBottom: 20,
  },
  buttonContainer: {
    padding: 20,
    paddingBottom: 60,
    width: "80%",
    alignSelf: "center",
  },
  //---------header-----------------------------
  topCard: {
    zIndex: 5,
    padding: 0,
    //position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: lightBlue,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    shadowColor: primaryColor,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 5,
    height: 80,

    zIndex: 999,
  },
  topCardExpanded: {
    zIndex: 5,
    padding: 0,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: secondaryColor,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    shadowColor: secondaryColor,
    shadowOffset: { width: 10, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 4,
    elevation: 5,
    height: ScreenHeight - 70,
  },
  GIACard: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: orange,
    marginLeft: 14,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
  },
  GIACardUnselected: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: orange,
    marginLeft: 14,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
    opacity: 0.5,
  },
  ISACard: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#FC007A",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
  },
  ISACardUnselected: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#FC007A",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 7,
    flexDirection: "column",
    opacity: 0.5,
  },
  practiceCard: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#00E1FD",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 14,
    flexDirection: "column",
  },
  practiceCardUnselected: {
    width: screenWidth / 2,
    height: ScreenHeight / 3.4,
    backgroundColor: "#00E1FD",
    marginLeft: 7,
    marginTop: 30,
    borderRadius: 10,
    marginRight: 14,
    flexDirection: "column",
    opacity: 0.5,
  },
  logoSegment: {
    height: 50,
    width: "100%",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 15,
    marginBottom: -10,
  },
  // headerBuffer: {
  //   height: 75,
  // },
  ballButton: {
    // backgroundColor: orange,
    borderColor: "#ff7f00",
    borderRadius: 10,
    borderWidth: 1,
    width: screenWidth / 3,
    height: 30,
    textTransform: "none",
    justifyContent: "center",
  },
  headerBall: {
    backgroundColor: orange,
    borderRadius: 20,
    color: "white",
  },
  catagory: {
    position: "absolute",
    right: 20,
    bottom: 10,
    fontFamily: font,
    fontSize: 20,
    backgroundColor: "transparent",
  },

  newsCard: {
    backgroundColor: secondaryColor,
    margin: 10,
    padding: 20,
  },
  stockNameView: {
    position: "absolute",
    top: 10,
    left: 65,
    height: 40,
    justifyContent: "center",
  },
  stockName: {
    fontSize: 13,
    fontFamily: font,
    fontWeight: "bold",
    color: "white",
  },
  stockTicker: {
    color: gray,
    fontFamily: font,
    letterSpacing: 1,
    fontWeight: "normal",
    textTransform: "uppercase",
    fontSize: 10,
    margin: 0,
  },
  priceView: {
    height: "50px",
    width: "50px",
    borderColor: "whitesmoke",
    borderWidth: 2,
  },
  priceContainer: {
    justifyContent: "center",
    marginRight: 10,
  },
  price: {
    fontSize: 20,
    borderRadius: 10,
    color: fontColor,
    fontFamily: font,
    alignSelf: "flex-end",
  },
  percentage: {
    fontSize: 12,
    fontFamily: font,
  },
  green: {
    fontSize: 12,
    color: green,
    fontWeight: "bold",
    alignSelf: "flex-end",
  },
  red: {
    fontSize: 12,
    color: red,
    fontWeight: "bold",
    alignSelf: "flex-end",
  },
  text: {
    fontSize: fontSizeTitle,
    fontFamily: font,
    color: fontColor,
    margin: 4,
  },
  textCenter: {
    fontSize: fontSizeTitle,
    fontFamily: font,
    color: fontColor,
    margin: 4,
    textAlign: "center",
  },
  centeredText: {
    fontSize: fontSizeTitle,
    fontFamily: font,
    color: fontColor,
  },
  titleText: {
    color: fontColor,
    fontFamily: font,
    letterSpacing: 2.5,
    fontWeight: "900",
    alignSelf: "center",
    fontSize: fontSizeTitle,
    margin: 1,
    fontSize: 15,
  },
  newsTitle: {
    color: fontColor,
    fontFamily: font,
    fontWeight: "700",

    fontSize: fontSizeTitle,
    margin: 4,
  },
  image: {
    borderRadius: 3,
    borderColor: "gainsboro",
    resizeMode: "contain",
    height: 40,
    width: 40,
    margin: 10,
    // backgroundColor: "white",
  },
  detailsImage: {
    marginTop: 20,
    marginBottom: 30,
    borderRadius: 40,
    resizeMode: "contain",
    justifyContent: "center",
    alignSelf: "center",
    height: 80,
    width: 80,
    // backgroundColor: "white",
  },
  avatarSmall: {
    margin: 20,
    width: 50,
    height: 50,
    justifyContent: "center",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 50,
    resizeMode: "contain",
  },
  footerText: {
    position: "absolute",
    bottom: 40,
    alignSelf: "center",
    color: fontColor,
  },
  rowSpaced: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  rowAround: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  //------------------------registration------------
  welcomeCard: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: secondaryColor,
    borderRadius: 15,
    height: 500,
  },
  logoStyle1: {
    height: screenWidth / 4,
    width: "25%",
    marginTop: 70,
    alignSelf: "center",
    resizeMode: "contain",
  },
  logoStyle2: {
    height: screenWidth / 3,
    width: "40%",
    marginTop: -12,
    marginBottom: 0,
    alignSelf: "center",
    resizeMode: "contain",
  },
  signupCard: {
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: secondaryColor,
    borderRadius: 15,
  },
  topView: {
    width: screenWidth,
    height: 50,
    backgroundColor: "red",
  },
  input: {
    width: screenWidth - 80,
    height: 40,
    backgroundColor: "lightgray",
    marginTop: 8,
    marginBottom: 0,
    alignSelf: "center",
    padding: 7,
    borderRadius: 10,
  },
  buttonReg: {
    width: screenWidth / 2,
    height: 40,
    backgroundColor: orange,
    alignSelf: "center",
    marginTop: 20,
    marginRight: screenWidth / 4 - 20,
    marginLeft: screenWidth / 4 - 20,
    borderRadius: 13,
    // position: "absolute",
    // bottom: 20,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    textTransform: "none",
  },
  orangeButtonText: {
    color: orange,
    fontWeight: "bold",
    textTransform: "none",
  },
  head1: {
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
    marginLeft: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  head2: {
    color: "white",
    fontWeight: "100",
  },
  loadBar: {
    height: 4,
    width: screenWidth - 80,
    backgroundColor: "#8d93a3",
    marginLeft: 40,
    borderRadius: 50,
    marginBottom: 20,
  },
  loadBar2Compleated: {
    backgroundColor: orange,
    height: 4,
    width: (screenWidth - 80) / 5,
    borderRadius: 50,
  },
  loadBar3Compleated: {
    backgroundColor: orange,
    height: 4,
    width: ((screenWidth - 80) / 5) * 2,
    borderRadius: 50,
  },
  loadBar4Compleated: {
    backgroundColor: orange,
    height: 4,
    width: ((screenWidth - 80) / 5) * 3,
    borderRadius: 50,
  },
  loadBar5Compleated: {
    backgroundColor: orange,
    height: 4,
    width: screenWidth - 80,
    borderRadius: 50,
  },
  warning: {
    color: "red",
    marginTop: 0,
    marginBottom: 0,
    marginLeft: 20,
    fontSize: 14,
  },
  noWarning: {
    opacity: 0,
  },
  imageContainer: {
    flex: 1,
    height: "28%",
    alignItems: "center",
    marginBottom: "2%",
    marginTop: 50,
    backgroundColor: "red",
  },
  bottomSubText: {
    color: "white",
    marginTop: 8,
    fontSize: 15,
  },
  hyperlinkText: {
    color: "#FF8001",
    fontWeight: "bold",
  },
  //--------------------menuscreen--------------------
  avatar: {
    width: 60,
    height: 60,
    justifyContent: "center",
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: 50,
    resizeMode: "cover",
    marginTop: 20,
  },
  menuName: {
    fontSize: 16,
    fontFamily: font,
    color: fontColor,
    alignSelf: "center",
    textAlign: "center",
    fontWeight: "bold",
  },
  menuEmail: {
    fontSize: 14,
    fontFamily: font,
    color: "gray",
    textAlign: "center",
    fontWeight: "100",
    alignSelf: "center",
  },
  settingsButton: {
    width: "100%",
    height: 50,
    backgroundColor: secondaryColor,
    marginBottom: 2,
    flexDirection: "column",
    justifyContent: "center",
  },
  settingsButtonTop: {
    width: "100%",
    height: 50,
    backgroundColor: secondaryColor,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginBottom: 2,
    marginTop: 5,
    flexDirection: "column",
    justifyContent: "center",
  },
  settingsButtonBottom: {
    width: "100%",
    height: 50,
    backgroundColor: secondaryColor,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    flexDirection: "column",
    justifyContent: "center",
    marginBottom: 20,
  },
  settingsCard: {
    marginLeft: 20,
    borderRadius: 10,
    marginRight: 20,
    marginTop: 0,
  },
  buttonTextSettings: {
    color: "white",
    fontWeight: "bold",
    textTransform: "none",
    backgroundColor: orange,
  },
  logout: {
    alignSelf: "center",
    justifyContent: "center",
    width: "45%",
    height: 45,
    borderColor: orange,
    borderWidth: 2,
    borderRadius: 14,
    marginTop: 10,
  },
  logoutText: {
    color: orange,
    fontWeight: "bold",
  },
  //--------history---------
  cardHeader: {
    fontSize: 18,
    marginTop: 10,
    marginLeft: 15,
    marginBottom: 10,
    color: gray,
  },
  cardDevider: {
    width: "100%",
    height: 2,
    backgroundColor: primaryColor,
  },
  cardHistory: {
    backgroundColor: secondaryColor,
    marginLeft: 10,
    marginBottom: 5,
    marginTop: 5,
    marginRight: 10,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  historyName: {
    fontSize: 19,
    color: "white",
  },
  historyAction: {
    fontSize: 10,
    color: "white",
    fontWeight: "100",
    color: gray,
  },
  historyValueBox: {
    position: "absolute",
    right: 10,
    height: "100%",

    justifyContent: "center",
  },
  historyValue: {
    fontWeight: "100",
    fontSize: 22,
    color: "white",
  },
  //------companyScreen------------
  card: {
    backgroundColor: secondaryColor,
    // height: 120,
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 0,
    marginRight: 10,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: secondaryColor,
    marginRight: 10,
    marginLeft: 10,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  cardTopList: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  priceInfo: {
    fontSize: 25,
    color: "whitesmoke",
    fontWeight: "100",
  },
  percentInfo: {
    fontSize: 12,
    color: "whitesmoke",
    fontWeight: "bold",
    letterSpacing: 2,
    alignSelf: "flex-end",
  },
  chartContainer: {
    backgroundColor: secondaryColor,
    marginRight: 10,
    marginLeft: 10,
    marginTop: 2,
  },
  chartButtons: {
    width: "100%",
    height: 40,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  chartIcon: {
    height: 30,
    width: (screenWidth - 90) / 6,
    margin: 5,
    justifyContent: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 10,
    opacity: 0.2,
  },
  selectedChartIcon: {
    height: 30,
    width: (screenWidth - 90) / 6,
    margin: 0,
    justifyContent: "center",
    backgroundColor: orange,
    justifyContent: "center",
    flexDirection: "row",
    borderRadius: 10,
    margin: 5,
    marginTop: 10,
  },
  chartTextButton: {
    color: "white",
    opacity: 0.9,
  },
  chartTextButtonOrange: {
    color: orange,
    opacity: 1,
    alignSelf: "center",
  },
  chartIconOrange: {
    height: 30,
    width: "16%",
    margin: 0,
    borderWidth: 1,
    borderColor: orange,
    color: orange,
    justifyContent: "center",
    borderRadius: 10,
  },
  orangeFillButton: {
    width: "48%",
    height: 45,
    paddingTop: 3.5,
    alignSelf: "center",
    backgroundColor: orange,
    borderRadius: 10,
  },
  FavouriteButton: {
    width: "48%",
    height: 45,
    paddingTop: 2,
    alignSelf: "center",
    borderWidth: 2,
    borderRadius: 10,
    borderColor: orange,
    backgroundColor: primaryColor,
  },
  infoCardTop: {
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    width: screenWidth - 20,
    backgroundColor: secondaryColor,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  infoCardBottom: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    width: screenWidth - 20,
    backgroundColor: secondaryColor,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  infoSection: {
    marginTop: 2,
    marginLeft: 10,
    marginRight: 10,
    height: 50,
    width: screenWidth - 20,
    backgroundColor: secondaryColor,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  infoTopText: {
    color: "white",
    fontSize: 15,
    letterSpacing: 1,
    marginLeft: 15,
  },
  infoContents: {
    backgroundColor: "#26325F",
    marginTop: 2,
    marginLeft: 10,
    marginBottom: 0,
    marginRight: 10,
    width: screenWidth - 20,
  },
  infoText: {
    color: "white",
    opacity: 0.7,
    marginTop: 10,
    marginRight: 10,
    marginLeft: 10,
    marginBottom: 10,
    letterSpacing: 1,
    fontSize: 16,
    lineHeight: 20,
  },
  listText1: {
    color: "white",
    opacity: 1,
    marginTop: 10,
    marginRight: 10,
    marginLeft: 20,
    marginBottom: 10,
    letterSpacing: 0,
    fontSize: 16,
    lineHeight: 20,
  },
  listText2: {
    color: "white",
    opacity: 0.75,
    marginTop: 10,
    marginRight: 20,
    marginLeft: 10,
    marginBottom: 10,
    letterSpacing: 0,
    fontSize: 16,
    lineHeight: 20,
  },
  //trade
  defaultTop: {
    marginTop: 10,
    marginLeft: 15,
    marginRight: 15,
    width: screenWidth - 30,
    backgroundColor: secondaryColor,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  selectedBuyButton: {
    backgroundColor: secondaryColor,
    width: "50%",
    borderTopLeftRadius: 10,
    color: "white",
    textAlign: "center",
    paddingTop: 14,
  },
  unselectedBuyButton: {
    backgroundColor: primaryColor,
    height: 50,
    width: "50%",
    borderTopLeftRadius: 10,
    color: "white",
    borderWidth: 2,
    borderColor: secondaryColor,
    textAlign: "center",
    paddingTop: 14,
  },
  selectedSellButton: {
    backgroundColor: secondaryColor,
    width: "50%",
    borderTopRightRadius: 10,
    color: "white",
    textAlign: "center",
    paddingTop: 14,
  },
  unselectedSellButton: {
    backgroundColor: primaryColor,
    height: 50,
    width: "50%",
    borderTopRightRadius: 10,
    color: "white",
    borderWidth: 2,
    borderColor: secondaryColor,
    textAlign: "center",
    paddingTop: 14,
  },
  defaultView: {
    marginTop: 2,
    marginLeft: 15,
    marginRight: 15,
    width: screenWidth - 30,
    backgroundColor: secondaryColor,
  },
  defaultCard: {
    marginTop: 5,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 2,
    width: screenWidth - 30,
    backgroundColor: secondaryColor,
    borderRadius: 10,
  },
  defaultInnerView: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
    marginBottom: 15,
  },
  defaultEndView: {
    marginTop: 0,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 10,
    width: screenWidth - 30,
    backgroundColor: secondaryColor,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  sharesView: {
    width: screenWidth - 30,
    height: 50,
    marginTop: 2,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: secondaryColor,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  tradeText: {
    color: "white",
    fontSize: 15,
    alignSelf: "center",
    marginLeft: 30,
    letterSpacing: 0.5,
    marginRight: 30,
  },
  tradeOrangeText: {
    color: orange,
    fontSize: 17,
    fontWeight: "bold",
    alignSelf: "center",
    marginLeft: 30,
    letterSpacing: 0.5,
    marginRight: 30,
  },
  sliderView: {
    width: screenWidth - 30,
    marginTop: 2,
    marginLeft: 15,
    marginRight: 15,
    backgroundColor: secondaryColor,
  },
  sliderText: {
    marginRight: 30,
    marginLeft: 30,
    marginTop: 15,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  yourShares: {
    color: "white",
    fontSize: 15,
    letterSpacing: 0.5,
  },
  amountOfShares: {
    width: 75,
    backgroundColor: gray,
    color: orange,
    textAlign: "center",
    borderRadius: 25,
    fontSize: 15,
    fontWeight: "bold",
  },
  slider: {
    marginTop: 10,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
  },
  tradeReviewButton: {
    alignSelf: "center",
    justifyContent: "center",
    width: "48%",
    height: 45,
    backgroundColor: orange,
    borderRadius: 14,
    marginTop: 30,
  },
  tradeCancleButton: {
    alignSelf: "center",
    justifyContent: "center",
    width: "48%",
    height: 45,
    backgroundColor: primaryColor,
    borderRadius: 14,
    marginTop: 30,
    borderWidth: 2,
    borderColor: orange,
  },
  portfolioInvested: {
    height: 70,
    width: "48%",
    backgroundColor: secondaryColor,
    flexDirection: "row",
    justifyContent: "center",
    borderRadius: 10,
  },

  portfolioChartHolder: {
    backgroundColor: secondaryColor,
    paddingBottom: 10,
    margin: 15,
    borderRadius: 10,
  },
  backgroundCard: {
    backgroundColor: secondaryColor,
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 5,
    marginRight: 10,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  backgroundSmallCardx3: {
    backgroundColor: secondaryColor,
    width: 130,
    height: 150,
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 0,
    marginRight: 0,
    borderRadius: 10,
    padding: 0,
    shadowColor: secondaryColor,
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
});

const button = StyleSheet.create({
  default: {
    backgroundColor: "#151D3E",
  },
});

export { styles, button };
